import { createClient } from '@supabase/supabase-js'

// You'll need to replace these with your actual Supabase project credentials
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || 'https://uozsfevsmkqmgcwgchxrv.supabase.co'
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvenNmZXZzbWtxbWdjd2hyeHJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4ODM4OTQsImV4cCI6MjA3NDQ1OTg5NH0.JGb3ByAApCZRqqchCrka2iKhSx0JODQiJKaoKyYkyyE'

export const supabase = createClient(supabaseUrl, supabaseAnonKey)

// Types for the requests table - Updated to match actual schema
export interface Request {
  id: number  // BIGINT GENERATED BY DEFAULT AS IDENTITY
  type: string  // request_type NOT NULL
  title: string  // TEXT NOT NULL
  createdat: string  // TIMESTAMPTZ DEFAULT now() (note: actual column name)
  addedby: string  // TEXT (note: actual column name)
}

export interface DashboardStats {
  totalRequests: number
  requestsByType: { type: string; count: number }[]
  requestsByAddedBy: { addedby: string; count: number }[]
  recentRequests: Request[]
}
