// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uozsfevsmkqmgcwhrxrv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvenNmZXZzbWtxbWdjd2hyeHJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4ODM4OTQsImV4cCI6MjA3NDQ1OTg5NH0.JGb3ByAApCZRqqchCrka2iKhSx0JODQiJKaoKyYkyyE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});